import type { Metadata } from 'next';
import Link from 'next/link';
import { PageHero } from '../_components/page-hero';
import { SiteFooter } from '../_components/site-footer';
import { SiteHeader } from '../_components/site-header';
import { customerOrganizations } from '../content';

export const metadata: Metadata = { title: 'Customer Deployments | Indian Infotech', description: 'Approved customer deployment stories and evidence-led case study framework for Indian Infotech.', alternates: { canonical: '/case-studies' } };
export default function CaseStudiesPage() { return <main><SiteHeader /><PageHero eyebrow="Customer proof" title="Real deployment stories, published when the evidence is approved." description="The legacy website publishes customer logos. Named challenges, architecture, products used, outcomes, quotes, and deployment photography will be added here only with permission and supporting material." marker="II / PROOF" /><section className="section"><div className="section-heading split-heading"><div><p className="section-kicker">Case study standard</p><h2>Customer. Challenge. Architecture. Outcome.</h2></div><p>Each story will explain the operating problem, hardware and software used, integration context, rollout, and approved outcome without turning a logo into an unsupported claim.</p></div><div className="proof-evidence-queue"><span>CASE STUDIES / EVIDENCE QUEUE</span><h2>No approved deployment stories published yet.</h2><p>Customer names and outcomes remain unpublished until permission and supporting evidence are confirmed.</p><Link className="button button-primary" href="/contact?topic=case-study">Submit deployment evidence <span aria-hidden="true">↗</span></Link></div></section><section className="section customer-roster"><div className="section-heading"><p className="section-kicker">Published legacy customer roster</p><h2>Organizations displayed on the current website.</h2></div><div className="customer-roster-grid">{customerOrganizations.map((customer) => <div key={customer.name}><span>{customer.name}</span><small>Logo source retained; case-study permission pending</small></div>)}</div></section><SiteFooter /></main>; }
