'use client';

import Image from 'next/image';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import type { IndustryProfile, Product, SolutionProfile, SoftwarePlatform } from '@/app/content';

type CompanySlide = { eyebrow: string; title: string; text: string; href: string; cta: string; image: string; alt: string };
const companySlides: readonly CompanySlide[] = [
  { eyebrow: '01 / COMPANY', title: 'Workforce and workplace systems, grounded in Ahmedabad.', text: 'Since 2011, Indian Infotech has built a published portfolio across biometric devices, access, entrance, workforce software, and HRMS workflows.', href: '/company', cta: 'Explore company', image: '/company/about-banner.png', alt: 'Indian Infotech workplace team' },
  { eyebrow: '02 / TRUST', title: 'Capability shown through the systems you can inspect.', text: 'Explore real product media, software routes, customer roster, support paths, and evidence standards across the site.', href: '/about', cta: 'Read about Indian Infotech', image: '/company/support-cta.png', alt: 'Indian Infotech support team' },
  { eyebrow: '03 / PORTFOLIO', title: 'From identity at the edge to workforce operations.', text: 'Connect attendance, controlled entry, visitor workflows, canteen operations, HRMS, and payroll planning around your facility.', href: '/platform', cta: 'See the platform', image: '/products/ai-60/angle.png', alt: 'AI 60 face recognition device' },
  { eyebrow: '04 / CONVERSATION', title: 'Start with the operating problem.', text: 'Bring workforce size, sites, entry points, software, and support needs to a practical solution conversation.', href: '/contact', cta: 'Talk to the team', image: '/products/fht2300/model-l.png', alt: 'FHT2300 full-height turnstile' },
];

export function CompanyShowcase() {
  const [active, setActive] = useState(0);
  useEffect(() => { const timer = window.setInterval(() => setActive((current) => (current + 1) % companySlides.length), 6500); return () => window.clearInterval(timer); }, []);
  const slide = companySlides[active];
  return <section className="home-company-showcase" aria-labelledby="home-company-title"><div className="home-company-copy"><p className="section-kicker light">{slide.eyebrow}</p><h2 id="home-company-title">{slide.title}</h2><p>{slide.text}</p><Link className="button button-primary" href={slide.href}>{slide.cta} <span aria-hidden="true">↗</span></Link><div className="showcase-controls" aria-label="Company slides">{companySlides.map((item, index) => <button type="button" key={item.eyebrow} onClick={() => setActive(index)} aria-label={`Show company slide ${index + 1}`} aria-current={index === active}>{String(index + 1).padStart(2, '0')}</button>)}</div></div><div className="home-company-image"><Image key={slide.image} src={slide.image} alt={slide.alt} width={1000} height={720} priority={active === 0} /></div></section>;
}

type TechnologyItem = { title: string; text: string; image: string; href: string; status?: string };
const technologyItems: readonly TechnologyItem[] = [
  { title: 'Face recognition', text: 'Published across AI-series attendance and access-control products.', image: '/products/ai-60/detail.png', href: '/technologies#identity' },
  { title: 'Fingerprint recognition', text: 'Published across access-control and attendance device offerings.', image: '/products/i-18.jpg', href: '/technologies#identity' },
  { title: 'RFID / card authentication', text: 'Review credential and access requirements during solution design.', image: '/products/is-500/main.png', href: '/technologies#identity' },
  { title: '3D structured-light facial recognition', text: 'Technology topic for technical review; product availability must be confirmed.', image: '/products/mini-ai-30/detail.png', href: '/technologies#identity', status: 'Review topic' },
  { title: 'Finger vein recognition', text: 'Technology topic for technical review; not presented as a published product claim.', image: '/products/ai-60/source-detail.png', href: '/technologies#identity', status: 'Review topic' },
  { title: 'Controlled entrance technology', text: 'Flap barriers, turnstiles, boom barriers, and screening equipment.', image: '/products/fbl-300/main.png', href: '/technologies#connected-systems' },
  { title: 'Attendance workflow technology', text: 'Device capture, software review, shifts, leave, and operational records.', image: '/products/mini-ai-10/front.png', href: '/technologies#workflow' },
];

export function TechnologyShowcase() { return <section className="home-showcase home-technology-showcase" aria-labelledby="home-technology-title"><div className="showcase-heading"><p className="section-kicker">02 / TECHNOLOGY</p><h2 id="home-technology-title">Identity and entry technology, shown with evidence status.</h2><p>Explore published capability and clearly marked technical review topics.</p><Link className="outline-link" href="/technologies">Explore technologies ↗</Link></div><div className="showcase-track">{technologyItems.map((item) => <Link className="showcase-card" href={item.href} key={item.title}><Image src={item.image} alt="" width={420} height={300} /><div><span>{item.status ?? 'Published portfolio'}</span><h3>{item.title}</h3><p>{item.text}</p><b>View technology ↗</b></div></Link>)}</div></section>; }

export function SolutionShowcase({ solutions }: { solutions: readonly SolutionProfile[] }) { return <section className="section home-showcase" aria-labelledby="home-solutions-title"><div className="showcase-heading"><p className="section-kicker">03 / SOLUTIONS</p><h2 id="home-solutions-title">Choose a solution around the work that needs to happen.</h2><p>Each card opens a real solution route with problem, workflow, hardware family, and software context.</p><Link className="outline-link" href="/solutions">View all solutions ↗</Link></div><div className="showcase-track light-track">{solutions.map((item) => <Link className="showcase-card solution-card" href={`/solutions/${item.slug}`} key={item.slug}><span className="card-number">{String(solutions.indexOf(item) + 1).padStart(2, '0')}</span><h3>{item.name}</h3><p>{item.summary}</p><b>Explore solution ↗</b></Link>)}</div></section>; }

export function SoftwareShowcase({ software, products }: { software: readonly SoftwarePlatform[]; products: readonly Product[] }) { const serviceLinks = [['Deployment and implementation', '/engineering'], ['Integration review', '/integrations'], ['Support and training', '/support'], ['HRMS and payroll workflows', '/software/hrms-payroll']] as const; return <section className="home-showcase home-software-showcase" aria-labelledby="home-software-title"><div className="showcase-heading"><p className="section-kicker light">04 / SOFTWARE + SERVICES</p><h2 id="home-software-title">More than devices: software, implementation, and support.</h2><p>Explore software routes, then move into engineering, integration, support, and training conversations.</p></div><div className="software-showcase-grid"><div className="software-showcase-panel"><span>Software platforms</span>{software.map((item) => <Link href={`/software/${item.slug}`} key={item.slug}><strong>{item.name}</strong><small>{item.modules.slice(0, 3).join(' · ')}</small><b>Open ↗</b></Link>)}</div><div className="software-showcase-panel"><span>Services</span>{serviceLinks.map(([label, href]) => <Link href={href} key={label}><strong>{label}</strong><small>Scope with responsible team</small><b>Open ↗</b></Link>)}<small className="software-product-note">{products.length} published product routes support solution design.</small></div></div></section>; }

export function IndustryShowcase({ industries }: { industries: readonly IndustryProfile[] }) { return <section className="section home-showcase" aria-labelledby="home-industries-title"><div className="showcase-heading"><p className="section-kicker">05 / INDUSTRIES</p><h2 id="home-industries-title">Operating context changes by industry.</h2><p>Start with site reality: shifts, visitors, controlled areas, contractors, people movement, and support ownership.</p><Link className="outline-link" href="/industries">Explore industries ↗</Link></div><div className="showcase-track industry-track">{industries.map((item, index) => <Link className="showcase-card industry-showcase-card" href={`/industries/${item.slug}`} key={item.slug}><span className="card-number">0{index + 1}</span><h3>{item.name}</h3><p>{item.context}</p><b>Explore industry ↗</b></Link>)}</div></section>; }
